[build-system]
requires = ["uv_build >= 0.11.7, <0.12.0"]
build-backend = "uv_build"

[project]
name = "gad245-g1-api"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13.7"

dependencies = [
    "alembic==1.18.4",
    "asyncpg==0.31.0",
    "authlib==1.6.0",
    "beanie==2.0.1",
    "cachetools==6.2.4",
    "chromadb==1.5.5",
    "fastapi[standard]>=0.136.3",
    "google-genai==1.59.0",
    "gradio==6.8.0",
    "huggingface-hub==0.34.4",
    "itsdangerous==2.2.0",
    "joblib==1.4.2",
    "langchain==0.3.23",
    "motor==3.7.0",
    "pandas==3.0.2",
    "pyarrow==19.0.1",
    "pydantic-settings==2.8.1",
    "pydantic[email]==2.12.5",
    "scikit-learn==1.6.1",
    "sqlalchemy[asyncio]==2.0.46",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.uv.build-backend]
module-name = ["app"]

[tool.uv]
link-mode = "copy"

[tool.pytest]
minversion = "9.0"
pythonpath = [ "src" ]
# -x, --exitfirst: Exit instantly on first error or failed test
# -v, --verbose: Increase verbosity of the test output
# -s: Disable output capture, so print() statements are shown directly in the console
# -m: Only run tests matching given mark expression
addopts = [
    "--strict-markers",
    "-xvs"
]
testpaths = [
    "tests"
]
anyio_mode = "auto"
markers = [
    "db",
    "hf",
    "test_only"
]
