[pytest]
testpaths = [ "tests" ]
pythonpath = [ "." ]
# -x, --exitfirst: Exit instantly on first error or failed test
# -v, --verbose: Increase verbosity of the test output
# -s: Disable output capture, so print() statements are shown directly in the console
# -m: Only run tests matching given mark expression
addopts = [ "--strict-markers", "-xvs" ]
anyio_mode = "auto"
markers = [
    "db",
    "hf",
    "test_only"
]