name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
    contents: 'read'
    id-token: 'write'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3   

    - name: Run tests
      run: |
        python --version
        pytest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: byckg3
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
          context: .
          push: true
          tags: ${{ vars.IMAGE_TAG }}

    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ secrets.SERVICE_NAME }}
        region: ${{ secrets.REGION }}
        image: ${{ vars.IMAGE_TAG }}
